### ISSUE TITLE
Return elevation profile in public transit mode

### ISSUE THREAD

**Issue by abhumbla** [bikehopper/graphhopper#14]
doesn't seem to be working, might be an issue with how the polyline is being encoded/decoded. might have to do it by leg
![broken_elevation](https://user-images.githubusercontent.com/9853610/153108569-118f830f-cfd1-4692-a376-23b95c9f5e29.png)

**Comment by graue** [comment]
Gonna need this to warn of steep hills on the frontend which I'd like to do soon!
