### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by ericcarlschwartz** [bikehopper/graphhopper#32]
Yo!

I see there are [contributing docs](https://github.com/bikehopper/graphhopper/blob/master/CONTRIBUTING.md) from the OG project and docs on how to [quickstart from source](https://github.com/bikehopper/graphhopper/blob/master/docs/core/quickstart-from-source.md)

Gonna play around with trying to get this built using those but let me know if I should be headed in another direction? 

I like writing docs so if I get this figured out / if someone can show me the right way I'll be happy to write something up 😛 

cc @Andykmcc @hcourt @abhumbla

**Comment by rsarathy** [comment]
Picking this up as part of our documentation push. The plan is to make a repository with markdown files, and then use `gh-pages` or something similar to serve them as a Wiki.

**Comment by Andykmcc** [comment]
I created a repo for general project docs and planning. It's bikehopper/bikehopper.

**Comment by rsarathy** [comment]
Oh oops, let me just make a `wiki` folder in there instead. No need for a separate repository in this case.

**Comment by Andykmcc** [comment]
Let me know if you need access permissions or whatever. I think I'm the only one who uses that repo at the moment.
