### ISSUE TITLE
Transfer to MUNI in market street subway

### ISSUE THREAD

**Issue by abhumbla** [bikehopper/graphhopper#49]
often you'll get routes that have you get off bart and take MUNI for a couple of stops that bart also goes to. this could never be faster, but it happens anyways. timetable issues in GTFS? some timing miscalculations by graphhopper? need to investigate. maybe this will go away after #39 
![unknown](https://user-images.githubusercontent.com/9853610/160036003-5fc5dc00-e88e-424e-aa86-653ce01bb651.png)

**Comment by graue** [comment]
Note that fixing #50 is going to make this specific problem moot, so we should only dig deep into this if we think it reflects a more general problem

**Comment by abhumbla** [comment]
investigating this, it doesn't appear to happen when `connecting_profile` is set to `foot`. so maybe this will be fixed by #39. i think it's exposing something interesting though, might dig into it more later

**Comment by graue** [comment]
This seems not relevant anymore
