### ISSUE TITLE
Bikes on Muni light rail are banned, so such routes shouldn't be returned

### ISSUE THREAD

**Issue by graue** [bikehopper/graphhopper#50]
We can either

- Manually mark Muni light rail lines (and streetcars and cable cars), somehow, as not allowing bikes; or,
- Override various other transit agencies' GTFS feeds that say that bikes aren't allowed while the official policy is actually that they are allowed. (We found at least one example of this - was it County Connection?)

This should block private beta, because we're pretty much immediately going to give people illegal routes through the Twin Peaks Tunnel and Sunset Tunnel, which we shouldn't do.

A more ambitious version of this issue would be to allow the user to specify if their bike is a folding bike, which _is_ allowed on Muni light rail, but still not allowed on Muni cable cars and historic streetcars. (See [Muni bike rules](https://www.sfmta.com/getting-around/bike/bikes-muni)) I don't think GTFS captures that complexity right now.

**Comment by abhumbla** [comment]
was thinking we should have `bikesAllowedOverride` as a request param with some structured data in operator/mode that allows us to specify where bikes are not allowed. and then have that as a hardcoded constant in the front end or in `bay-area-config.yml` (whatever makes the most sense philosophically)

**Comment by hcourt** [comment]
We're not returning these anymore, but it would be a good idea to no longer hardcode these fixes.  In the mid term, by having some pre-build step that uses https://github.com/interline-io/transitland-lib to fix data. In the long term, by fixing the data in the GTFS feed itself.
