### ISSUE TITLE
rotate 511 api key

### ISSUE THREAD

**Issue by Andykmcc** [bikehopper/graphhopper#52]
we should make a new secret, add it to kube secrets, then update the code to use the new one from secrets. The main reason we should do this is because it is committed to this public repo, so anyone could be using it right now. 

https://github.com/bikehopper/graphhopper/blob/master/k8s/build-graphhopper-graph-cache.job.yml#L39

**Comment by graue** [comment]
@Andykmcc this is done, right?

**Comment by rsarathy** [comment]
gentle bump, is this completed?

**Comment by Andykmcc** [comment]
It must be. I don't even know what this is referring too. But we do t have any keys in got so far as I know.
