### ISSUE TITLE
Prioritize Bike Network

### ISSUE THREAD

**Issue by hcourt** [bikehopper/graphhopper#55]
The router doesn't prefer (for example) Middle Drive West, even though it's an official bike route, and takes a seemingly non-official cyclepath instead.

![image](https://user-images.githubusercontent.com/2773087/160722465-e27fd4bf-8758-476e-9505-0801c807bfdc.png)

Maybe this means we edit OSM, or maybe we update the encoder.

**Comment by rsarathy** [comment]
Closing this now too, a-la what was discussed in #33. Bike routes going through GGP are using Middle Drive connecting to JFK.

[Example](https://bikehopper.org/route/Ocean%20Beach@-122.51018496812173,37.756151349999996/to/Castro%20District%2C%20San%20Francisco%2C%2094114@-122.434957,37.7608561)
