### ISSUE TITLE
Use env variables to point to OSM/gtfs

### ISSUE THREAD

**Issue by abhumbla** [bikehopper/graphhopper#6]
Currently the data files are in bay-area/config.yml as /mnt/store/current-norcal-latest.osm.pbf
Make the /mnt/store an env variable so we can make it easier to develop locally

**Comment by rsarathy** [comment]
Closing this because I think our local development setup is in a good place now. It looks like Andy tried this in PR #3 but reverted back to the datapaths that we have now (e.g. `data/norcal-latest.osm.pbf`).
