### ISSUE TITLE
Certain points aren't routable

### ISSUE THREAD

**Issue by abhumbla** [bikehopper/graphhopper#65]
Not sure if this is a snapping problem? but for example the geocoded result for Fremont, CA is not routable. 
![snap-error](https://user-images.githubusercontent.com/9853610/163873384-3a8b8b1f-9b0b-4f2a-a3f8-d3d2924364c9.png)

**Comment by abhumbla** [comment]
can't seem to reproduce this, if it doesn't happen again let's close

**Comment by graue** [comment]
Not seeing any more evidence of this happening, closing
