### ISSUE TITLE
Make sure Arrive By routing works

### ISSUE THREAD

**Issue by graue** [bikehopper/graphhopper#66]
We have not tested this as we didn't have UI for it; let's make sure it gives reasonable results.

**Comment by hcourt** [comment]
Initial testing in the graphhopper UI seems like it works, on master. We need to add the UI bit to be sure, though.

**Comment by hcourt** [comment]
![image](https://user-images.githubusercontent.com/2773087/164342482-c96c87d4-afcd-4e3c-bd28-77bcf29fe46f.png)

Yep, looks like this works and gives reasonable routes. (in the above, pt.arrive_by=true and the time was set to 4:45)
