### ISSUE TITLE
Reading edges the wrong way on interpolated legs

### ISSUE THREAD

**Issue by abhumbla** [bikehopper/graphhopper#67]
for some reason the code to turn interpolated transfers into legs is failing a check making sure the edge is being read in the correct direction. not sure why this is happening. graphhopper upstream might have fixed this already. we should check that. I've commented out the check for now, doesn't seem to cause any problems
![reverse-edge-error](https://user-images.githubusercontent.com/9853610/164109744-2d211f52-0cb3-44c3-a88d-74b1b603f032.png)

**Comment by rsarathy** [comment]
I wasn't able to reproduce this with the above query and the code uncommented. The edge in question is Bailey Road in Pittsburg, and I tried routing through it to produce the exception, but all queries succeeded. Are there other ways to exercise this check?

**Comment by abhumbla** [comment]
hmm, maybe this got fixed with the change we made yesterday to the interpolated transfers? I would play around with this but if we can't replicate, I think it's fine to uncomment the check and close the issue

**Comment by rsarathy** [comment]
Just reproduced this with one of our cases (Jack London Square -> Levi's Stadium departing at 21 May 2024 14:30) that we used to debug #68. Scott's change yesterday fixes this issue too.
