### ISSUE TITLE
Handle elevation better

### ISSUE THREAD

**Issue by abhumbla** [bikehopper/graphhopper#69]
We should:
- estimate time better for steep streets
- add penalties for very steep streets

currently it prefers steiner over polk/arguello, we should tweak until it doesn't
![steiner](https://user-images.githubusercontent.com/9853610/164119169-7ee9fea8-e7aa-484e-aa99-d83707765f80.png)

**Comment by hcourt** [comment]
Closed by #101. Now it doesn't take polk/arguello, but the route it takes now is reasonable -- going through the west of presidio.
