### ISSUE TITLE
Snap to streets, not separately-mapped sidewalks

### ISSUE THREAD

**Issue by graue** [bikehopper/graphhopper#74]
When sidewalks are mapped separately on OSM, the router's directions start out in a needlessly confusing and awkward way, for example in these instructions starting from a randomly chosen address on Shotwell Street in SF:

![image](https://user-images.githubusercontent.com/1730853/164966057-039dae1b-1378-4fef-b23d-cff550883fb6.png)

First 3 instructions:

1. Continue [translated by the UI I've built into "Head north"]
2. Turn right
3. Turn right onto Shotwell Street

After this, the instructions are normal. But people are going to be confused by the first two instructions referring to unnamed pathways (which are in fact the Shotwell Street sidewalk and the 19th Street sidewalk, respectively). The instructions should just begin with:

1. Head south on Shotwell Street

**Comment by graue** [comment]
Related issue: we're producing this inscrutable set of directions for crossing the street where just "Get off at 24th St & Mission St, Board BART at 24th Street / Mission" would be plenty of information:

![image](https://user-images.githubusercontent.com/1730853/168155361-03fb2618-38c3-4c30-b949-bbebe3b9aee5.png)

![image](https://user-images.githubusercontent.com/1730853/168155567-ff6d53ba-3276-4223-9272-bb19d605257a.png)

**Comment by graue** [comment]
I wonder if we could solve this by just not snapping to a way tagged with [footway=sidewalk](https://wiki.openstreetmap.org/wiki/Tag:footway=sidewalk), since, in those cases, there should always be a nearby way that represents the street.

**Comment by Andykmcc** [comment]
there is a `snap_preventions` option that lets you provide a list of ways. its ref'd in this [issue](https://discuss.graphhopper.com/t/difference-between-snap-prevention-and-custom-model/7933) and i've seen in in other docs over the last week. my gut says we can add this to our profile in the config.yml

**Comment by rsarathy** [comment]
Graphhopper's provided `snap_preventions` and `SnapPreventionEdgeFilter` APIs only work for non-PT profiles. I'm working on incorporating the `SnapPreventionEdgeFilter` into our PT routing methods.
