### ISSUE TITLE
Prefer less steep bike routes

### ISSUE THREAD

**Issue by graue** [bikehopper/graphhopper#81]
The below route (among other unrelated issues) puts you on a 21% grade for one block of Ridgewood, even though a <10% grade path is possible and only slightly longer:

![image](https://user-images.githubusercontent.com/1730853/169735285-95b16ec5-676b-4710-ac13-9627fc810eb1.png)

Suggestion: The router should prefer avoiding 12-15% grades, strongly prefer avoiding 16-20% grades, and only do >20% if necessary to reach destination.

(Just a starting point for discussion; open to different approaches that might turn out to be easier to implement, or tweaking this if it's too strict and creates very circuitous routes, etc.)

**Comment by graue** [comment]
My understanding is that the router currently takes into account how elevation affects speed -- so it may be thinking that even with the steep grade, going directly up that 21% grade block is like 30 seconds faster than going around -- but it doesn't factor in that going around may be much more comfortable because the extremely steep grade is specifically exhausting.

**Comment by hcourt** [comment]
Closed by #101
