### ISSUE TITLE
Be less silly about avoiding bad bike infra for very short lengths

### ISSUE THREAD

**Issue by graue** [bikehopper/graphhopper#96]
Example: any route that has you go south on Bayshore Blvd around the Bayshore Caltrain makes you go into this gas station

![image](https://user-images.githubusercontent.com/1730853/185711470-99fa3b09-ce95-43f6-a5e3-be7bebbf52fe.png)

It's trying to avoid this stretch where Bayshore's bikelane disappears for double right turn lanes

![bah](https://user-images.githubusercontent.com/1730853/185711626-37efec70-1fa6-4ee3-93fe-d9012cf41263.jpg)

However the suggestion doesn't even avoid the actual turn conflict, as it has you reenter Bayshore Blvd only halfway down the block.

@arindam1993 suggests we not weight so strongly against bad infra if it's a very short length of bad infra

**Comment by graue** [comment]
Another example
![image](https://user-images.githubusercontent.com/1730853/185720538-dccd9fd9-4295-4a50-ac01-6ecb3c923637.png)

**Comment by rsarathy** [comment]
Interestingly, the Bayshore Blvd case seems to be [fixed](https://bikehopper.org/route/-122.4032340846201,37.711625407251205/to/-122.39838126842409,37.68569068388538).

In the second example, we don't employ that triangular dogleg [anymore](https://bikehopper.org/route/-122.45913746595988,37.7469812947019/to/-122.45690681367387,37.744955230357974). However, BH avoids that stretch of Laguna Honda altogether on longer routes in favor of a pair of quieter residential streets.

**Comment by graue** [comment]
Huh. I wonder what changed that!

The related case in #161 still repros, but I'll close since we don't have a separate example of this anymore.
